## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.6"
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - python: "2.7"

install: make init
script: make test

