## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

install: pip install .

script: python setup.py test
