## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python

os: linux

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # python 3.7 is only available on xenial

notifications:
  email: false

install: pip install .

script: python setup.py test
