## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.6"
notifications:
  email: false
git:
  depth: 99999999

# Travis on Apple is currently not able to install python...
matrix:
  allow_failures:
    - os: osx
    - python: "2.7"

install: make init
script: make test

